# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - AppHeader

name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Build website
      run: |
        npm install
        npm run build:webpack
        
    - name: Copy files
      uses: ulaval/azure-blob-copy-action@v1
      with:
        action: upload
        connection_string: https://singlespa.blob.core.windows.net/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-07-18T19:02:13Z&st=2022-07-18T11:02:13Z&spr=https&sig=h3UQyc5XwDcZA%2Fxh5Q4xu8Qg7fAPTEn82VNBWAx4nHU%3D
        container_name: $react-header
        local_directory: dist
        http_headers: |
          - glob: "**/*.????????.*"
            headers:
              Cache-Control: public, max-age=604800, immutable

          - glob: "**/*"
            headers:
              Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate
    # - name: Deploy to Azure
    #   uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
    #   with:
    #     source-path: dist
    #     container: react-header
    #     sas-url: https://singlespa.blob.core.windows.net/?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-07-18T19:02:13Z&st=2022-07-18T11:02:13Z&spr=https&sig=h3UQyc5XwDcZA%2Fxh5Q4xu8Qg7fAPTEn82VNBWAx4nHU%3D

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js version
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16.x'

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build:webpack

#      - script: |
#               mkdir $(Build.ArtifactStagingDirectory)\\dist
#               xcopy "$(System.DefaultWorkingDirectory)\\AppHeader\\dist" $(Build.ArtifactStagingDirectory)\\dist /E/H/C
#             displayName: Copy dist contents

#     - task: PublishBuildArtifacts@1
#             displayName: "Publish Artifact"

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#           name: node-app

#       - name: 'Deploy to Azure Web App'
#         uses: azure/webapps-deploy@v2
#         id: deploy-to-webapp
#         with:
#           app-name: 'AppHeader'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BD15D3AADC4D4E6AAD20D6C03C6221C8 }}
#           package: .


# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
#   branches:
#     include:
#       - main
#   paths:
#     include:
#       - AppHeader

# stages:
#   - stage: Build
#     pool:
#       vmImage: "windows-latest"
#     jobs:
#       - job: Build
#         displayName: "React App Build"
#         workspace:
#           clean: all
#         steps:
#           - task: NodeTool@0
#             inputs:
#               versionSpec: "16.x"
#             displayName: "Install Node.js"

#           - task: Npm@1
#             inputs:
#               command: "install"
#               workingDir: "$(System.DefaultWorkingDirectory)/AppHeader"
#             displayName: "Npm Install"

#           - task: Npm@1
#             inputs:
#               command: custom
#               customCommand: "run build:webpack"
#               workingDir: "$(System.DefaultWorkingDirectory)/AppHeader"
#             displayName: "Build React app"

#           - script: |
#               mkdir $(Build.ArtifactStagingDirectory)\\dist
#               xcopy "$(System.DefaultWorkingDirectory)\\AppHeader\\dist" $(Build.ArtifactStagingDirectory)\\dist /E/H/C
#             displayName: Copy dist contents

#           - task: PublishBuildArtifacts@1
#             displayName: "Publish Artifact"

#   - stage: Deploy
#     dependsOn: Build
#     condition: succeeded('Build')
#     variables:
#       - group: SECRET-DEV
#       - group: VGRP-DEV
#     pool:
#       vmImage: "windows-latest"
#     jobs:
#       - deployment: Deploy
#         displayName: Deploy to Azure
#         environment: DEV
#         strategy:
#           runOnce:
#             deploy:
#               steps:
#                 - task: AzureCLI@2
#                   displayName: "Deploy React app"
#                   inputs:
#                     azureSubscription: $(azureSubscription)
#                     scriptType: batch
#                     scriptLocation: inlineScript
#                     inlineScript: |
#                       az storage blob upload-batch --overwrite -d react-header --account-name $(storageAccount) --account-key $(accountkey) -s "$(Agent.BuildDirectory)\\drop\\dist"
