# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - AppHeader

name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Build website
      run: |
        npm install
        npm run build:webpack
        
    - name: Copy files
      uses: ulaval/azure-blob-copy-action@v1
      with:
        action: upload
        connection_string: BlobEndpoint=https://singlespa.blob.core.windows.net/;QueueEndpoint=https://singlespa.queue.core.windows.net/;FileEndpoint=https://singlespa.file.core.windows.net/;TableEndpoint=https://singlespa.table.core.windows.net/;SharedAccessSignature=sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2022-07-19T14:41:36Z&st=2022-07-19T06:41:36Z&spr=https&sig=%2Fnm%2B5lGJ4yITaNyHJ90J5bdPNtNFZaWBLTuASGhcHpI%3D
        container_name: react-header
        local_directory: dist
        http_headers: |
          - glob: "**/*.????????.*"
            headers:
              Cache-Control: public, max-age=604800, immutable

          - glob: "**/*"
            headers:
              Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate
