# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - AppHeader

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js version
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16.x'

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build --if-present
#           npm run test --if-present
#           npm run build:webpack

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v2
#         with:
#           name: node-app
#           path: .

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#           name: node-app

#       - name: 'Deploy to Azure Web App'
#         uses: azure/webapps-deploy@v2
#         id: deploy-to-webapp
#         with:
#           app-name: 'AppHeader'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BD15D3AADC4D4E6AAD20D6C03C6221C8 }}
#           package: .


# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - react-app

stages:
  - stage: Build
    pool:
      vmImage: "windows-latest"
    jobs:
      - job: Build
        displayName: "React App Build"
        workspace:
          clean: all
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "install"
              workingDir: "$(System.DefaultWorkingDirectory)/react-app"
            displayName: "Npm Install"

          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run build:webpack"
              workingDir: "$(System.DefaultWorkingDirectory)/react-app"
            displayName: "Build React app"

          - script: |
              mkdir $(Build.ArtifactStagingDirectory)\\dist
              xcopy "$(System.DefaultWorkingDirectory)\\react-app\\dist" $(Build.ArtifactStagingDirectory)\\dist /E/H/C
            displayName: Copy dist contents

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact"

  - stage: Deploy
    dependsOn: Build
    condition: succeeded('Build')
    variables:
      - group: SECRET-DEV
      - group: VGRP-DEV
    pool:
      vmImage: "windows-latest"
    jobs:
      - deployment: Deploy
        displayName: Deploy to Azure
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: "Deploy React app"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: batch
                    scriptLocation: inlineScript
                    inlineScript: |
                      az storage blob upload-batch --overwrite -d react-microapp --account-name $(storageAccount) --account-key $(accountkey) -s "$(Agent.BuildDirectory)\\drop\\dist"